name: Robot Framework Tests

on:
  push:

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Robot Framework tests
        run: robot -v BROWSER:headlesschrome -d results .

      - name: Upload Robot Framework results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/